# Generated by Django 5.0.2 on 2025-07-09 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_complaint_created_at_complaint_satisfaction_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.agency'),
        ),
    ]
